name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for modified files
      run: |
        if git diff --name-only HEAD^ | grep -E '^crypt.py$|^test.py$'; then
          echo "Les fichiers crypt.py et test.py ne doivent pas être modifiés."
          exit 1
        fi

  run_tests:
    runs-on: ubuntu-latest
    needs: check_files

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover
